### ISSUE TITLE
Question: Does Post-Process always move to work origin?

### ISSUE THREAD

**Issue by tylerhartwig** [nunorvoliveira/snapmaker-2.0#7]
Hi, wondering if the post-processor always sends to work origin? 

I sometimes set my work origin to be under the part (makes setting the z-origin pretty easy). This may be a horrible practice, but wondering if I should avoid doing that if I'm using this post-processor.

**Comment by nunorvoliveira** [comment]
Hello,

To be 100% honest I don't know for sure. It's been a long time since I had the machine running.
What I know is that I faced the same problem, both on the beginning and at the end of the machining, and on my post processor it is supposed to keep the Z axis at the safe retract height.

You can simulate it to be sure, but in theory, the Z axis only goes down to do actual CNC work and at the end of the CNC program, it will raise before letting the snapmaker machine do any horizontal moves.

**Comment by tylerhartwig** [comment]
Gotcha, that is helpful, it sounds like "Move to work origin" then means in the X and Y plane, and not in Z, thanks!
